#配置端口号
server:
  port: 8001

#配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jsako.springcloud.entities

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: SSYVcal262